LANG = 'en'    #[en/fr]

TEMP_SETTING = 'Cell'    #[Ambient/Cell]

Eg_REF = 1.796e-19    #Band gap energy for Si at standard test conditions (J)
                      #Modify according to semiconductor material

[FONT]
family = 'Microsoft Sans Serif'
color = '#000000'
weight = 'bold'
size = '10'

[UNITS]
temperature = 'C'    #[C/F]
length = 'mm'    #[mm/in]